version: '3'

services:
  
  postgres:

    image: docker.io/postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pw

    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data

    secrets:
      - postgres_pw


secrets:
  postgres_pw:
    file: ./secrets/postgres_pw.txt
